baseURL = 'https://ludohirst.me/'
locale = 'en-gb'
title = 'maths blog'
theme = "hugo-bearblog"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]
