baseURL = 'https://ludohirst.me/'
locale = 'en-gb'
title = 'maths blog'
author = "Ludo Hirst"
theme = "hugo-bearblog"

[params]
  hideMadeWithLine = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]
